package com.emlogis.engine.domain.contract;

public enum ConstraintOverrideType {

    MAX_CONSECUTIVE_DAYS_OVERRIDE,
    PTO_OVERRIDE,
    ALL_DAY_UNAVAILABLE_OVERRIDE,
    TIME_WINDOW_UNAVAILABLE_OVERRIDE,
    WEEKDAY_ROTATION_OVERRIDE,
    COUPLED_WEEKEND_OVERRIDE,
    DAYS_OFF_AFTER_OVERRIDE,
    DAYS_OFF_BEFORE_OVERRIDE,
    MIN_HOURS_BETWEEN_DAYS_OVERRIDE,
    MIN_HOURS_DAY_OVERRIDE,
    MAX_HOURS_DAY_OVERRIDE,
    MAX_HOURS_WEEK_OVERRIDE,
    MAX_DAYS_WEEK_OVERRIDE,
    MIN_HOURS_WEEK_OVERRIDE,
    EMPLOYEE_UNAVAILABLE,
    AVOID_OVERTIME,
    TEAM_FLOAT_ON

}
